project:
  type: website

website:
  favicon: assets/favicon.ico
  google-analytics: "UA-XXXXXXXX"
  title: "Ket Zaly"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - projects/index.qmd
      - href: about.qmd
        text: About
      - resume.qmd
  page-footer:
    background: light # or `dark`
    left: Copyright 2025, Ket Zaly
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: 
      light: flatly
      dark: solar
    fontsize: 1em
    css: styles.css
    toc: true



